services:
  postgress:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: alok
      POSTGRES_PASSWORD: alok24
      POSTGRES_DB: alokhealthcare
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: nextjs_app
    ports:
      - '3000:3000'
    environment:
<<<<<<< HEAD
      - DATABASE_URL: postgresql://alok:alok24@178.16.139.84:5432/alokhealthcare

=======
      - DATABASE_URL: postgresql://alok:alok24@postgres:5432/alokhealthcare
>>>>>>> 4e87e94cfd06627f97fe2cc1a4b827face79bf3a
    depends_on:
      - postgres

volumes:
  postgres_data:
