version: '3.8'

services:
  postgress:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: alok
      POSTGRES_PASSWORD: alok24
      POSTGRES_DB: alokhealthcare
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: nextjs_app
    ports:
      - '3000:3000'
    environment:
      - DATABASE_URL: postgresql://alok:alok24@postgres:5432/alokhealthcare
    depends_on:
      - postgres

volumes:
  postgres_data:
